"""added created_at column in applications table

Revision ID: 80eacd1b406d
Revises: fb082ad5dc94
Create Date: 2026-04-11 16:07:59.920208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80eacd1b406d'
down_revision: Union[str, Sequence[str], None] = 'fb082ad5dc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
