"""separated experience from aplications table

Revision ID: fb082ad5dc94
Revises: 34dcd946270f
Create Date: 2026-04-11 16:03:53.933504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb082ad5dc94'
down_revision: Union[str, Sequence[str], None] = '34dcd946270f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'open_to_relocate')
    op.drop_column('applications', 'current_ctc')
    op.drop_column('applications', 'total_experience')
    op.drop_column('applications', 'current_company')
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'notice_period')
    op.drop_column('applications', 'expected_ctc')
    op.drop_column('applications', 'location_preference')
    op.drop_column('applications', 'current_job_title')
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'relevent_experience')
    op.drop_column('candidate_accounts', 'resume_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_accounts', sa.Column('resume_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('relevent_experience', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('current_job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('location_preference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('expected_ctc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('notice_period', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('current_company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('total_experience', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('current_ctc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('open_to_relocate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
