"""added certificate_path column

Revision ID: 18fa38aea10e
Revises: 80eacd1b406d
Create Date: 2026-04-11 22:46:24.521954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fa38aea10e'
down_revision: Union[str, Sequence[str], None] = '80eacd1b406d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('certificate_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'certificate_path')
    # ### end Alembic commands ###
