"""removed dob

Revision ID: 34dcd946270f
Revises: 
Create Date: 2026-04-10 22:42:17.160076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34dcd946270f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    op.add_column('applications', sa.Column('job_id', sa.String(), nullable=False))
    op.alter_column('applications', 'total_experience',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('applications', 'relevent_experience',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('applications', 'current_company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'current_job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'notice_period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'current_ctc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('applications', 'expected_ctc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'applications', 'job_descriptions', ['job_id'], ['id'])
    op.drop_column('candidate_profiles', 'country')
    op.drop_column('candidate_profiles', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('candidate_profiles', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.alter_column('applications', 'expected_ctc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('applications', 'current_ctc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('applications', 'notice_period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'current_job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'current_company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'relevent_experience',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('applications', 'total_experience',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('applications', 'job_id')
    op.create_table('candidates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chroma_vector_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_education', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experience_years', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('applied_jd_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interview_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interview_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interview_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aadhar_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('validation_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_certifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('candidates_pkey')),
    sa.UniqueConstraint('email', name=op.f('candidates_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
