"""added file_path column

Revision ID: 7487cf55f4c8
Revises: 18fa38aea10e
Create Date: 2026-04-14 23:05:36.979023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7487cf55f4c8'
down_revision: Union[str, Sequence[str], None] = '18fa38aea10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aadhar_details')
    op.drop_table('audio_transcriptions')
    op.drop_table('document_extractions')
    op.drop_table('pan_details')
    op.drop_table('educational_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('candidate_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roll_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('institution_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('board_university', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('passing_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('percentage_cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('educational_details_pkey'))
    )
    op.create_table('pan_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pan_no', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fathers_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pan_details_pkey')),
    sa.UniqueConstraint('pan_no', name=op.f('pan_details_pan_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('document_extractions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doc_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_accounts.id'], name=op.f('document_extractions_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_extractions_pkey'))
    )
    op.create_table('audio_transcriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audio_transcriptions_pkey'))
    )
    op.create_table('aadhar_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aadhar_no', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aadhar_details_pkey')),
    sa.UniqueConstraint('aadhar_no', name=op.f('aadhar_details_aadhar_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
